version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www
    depends_on:
      - db
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    expose:
        - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/tmp/dump.sql

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:80"
    depends_on:
      - php

volumes:
  db_data:
